'use strict';
const fs=require('fs');const path=require('path');
const ROLES=Object.freeze({
  evaluator:{id:'psychological-evaluator',name:'Psychological Evaluator',scope:'Structured wellbeing screening and reflection only; no diagnosis or forensic fitness assessment.'},
  psychiatry:{id:'psychiatry-support',name:'Psychiatry Support',scope:'Medication and care-navigation education only; no prescribing, diagnosis, or dose changes.'},
  counsellor:{id:'counsellor',name:'Counsellor',scope:'Supportive listening, coping and planning; not emergency or licensed clinical care.'},
  growth:{id:'emotional-self-improvement',name:'Emotional Self-Improvement Specialist',scope:'Goals, habits, reflection and emotional skills; no clinical claims.'}
});
const clamp=(n)=>Number.isInteger(Number(n))&&Number(n)>=0&&Number(n)<=3?Number(n):null;
function level(score,cuts){for(const [min,label] of cuts)if(score>=min)return label;return 'minimal';}
class MentalHealthService{
  constructor({root=__dirname,audit=null}={}){this.audit=audit;this.file=path.join(root,'state','mental-health.json');this.state={format:'mental-health/1',consent:false,trainingEligible:false,retrievalEligible:false,records:[]};this._load();}
  _load(){try{const x=JSON.parse(fs.readFileSync(this.file,'utf8'));if(x&&x.format==='mental-health/1')this.state={...this.state,...x,trainingEligible:false,retrievalEligible:false};}catch{}}
  _save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const t=this.file+'.tmp-'+process.pid;fs.writeFileSync(t,JSON.stringify(this.state,null,2)+'\n',{mode:0o600});fs.renameSync(t,this.file);}
  status(){return{state:'SUCCESS',format:'mental-health/1',consent:!!this.state.consent,roles:Object.values(ROLES),trainingEligible:false,retrievalEligible:false,records:this.state.records.length,boundaries:['NO_DIAGNOSIS','NO_PRESCRIBING','NO_SILENT_THIRD_PARTY_CONTACT','OWNER_SESSION_PROTECTED']};}
  setConsent(value){this.state.consent=!!value;this._save();this.audit?.('mental-health',this.state.consent?'consent enabled':'consent disabled','user');return this.status();}
  screen({phq9=[],gad7=[],note=''}={}){if(!this.state.consent)return{state:'BLOCKED',message:'Explicit mental-health consent is required before screening.'};if(phq9.length!==9||gad7.length!==7)return{state:'DENIED',message:'PHQ-9 requires 9 answers and GAD-7 requires 7 answers.'};const p=phq9.map(clamp),g=gad7.map(clamp);if(p.includes(null)||g.includes(null))return{state:'DENIED',message:'Screening answers must be integers from 0 to 3.'};const phq9Score=p.reduce((a,b)=>a+b,0),gad7Score=g.reduce((a,b)=>a+b,0);const safetySignal=p[8]>0;const result={state:'SUCCESS',kind:'screening-support',notDiagnosis:true,phq9:{score:phq9Score,band:level(phq9Score,[[20,'severe'],[15,'moderately-severe'],[10,'moderate'],[5,'mild']])},gad7:{score:gad7Score,band:level(gad7Score,[[15,'severe'],[10,'moderate'],[5,'mild']])},safety:{signal:safetySignal,message:safetySignal?'A self-harm response was indicated. Seek immediate human support or emergency help if there is imminent danger; WitForge does not silently contact anyone.':'No self-harm response was indicated in this screening.'},trainingEligible:false,retrievalEligible:false};
    const record={id:'mh-'+Date.now(),createdAt:new Date().toISOString(),...result,note:String(note||'').slice(0,1000)};this.state.records.push(record);this.state.records=this.state.records.slice(-100);this._save();this.audit?.('mental-health','screening recorded locally','user');return result;}
  support({role='counsellor',message=''}={}){if(!this.state.consent)return{state:'BLOCKED',message:'Explicit mental-health consent is required.'};const selected=Object.values(ROLES).find(r=>r.id===role)||ROLES[role]||ROLES.counsellor;return{state:'SUCCESS',role:selected,input:String(message||'').slice(0,2000),guidance:{scope:selected.scope,principles:['reflect the user’s stated concerns','offer practical low-risk coping or planning ideas','encourage qualified human care when needs exceed role scope','escalate only by recommending emergency help when imminent danger is described']},trainingEligible:false,retrievalEligible:false};}
  deleteAll(confirm=''){if(String(confirm)!=='DELETE MENTAL HEALTH DATA')return{state:'DENIED',message:'Exact confirmation DELETE MENTAL HEALTH DATA is required.'};this.state={format:'mental-health/1',consent:false,trainingEligible:false,retrievalEligible:false,records:[]};try{fs.rmSync(this.file,{force:true});}catch{}this.audit?.('mental-health','mental-health records explicitly deleted','user');return{state:'SUCCESS',deleted:true};}
}
module.exports={MentalHealthService,MENTAL_HEALTH_ROLES:ROLES};