'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ACTIONS=['UP','RIGHT','DOWN','LEFT'];const V={UP:[0,-1],RIGHT:[1,0],DOWN:[0,1],LEFT:[-1,0]};
const key=(s)=>[Math.sign(s.apple[0]-s.head[0]),Math.sign(s.apple[1]-s.head[1]),...ACTIONS.map(a=>s.danger[a]?1:0)].join(',');
function rng(seed){let x=(seed>>>0)||1;return()=>((x=(1664525*x+1013904223)>>>0)/4294967296);}
class SnakeLab{
 constructor({root=__dirname,audit=null}={}){this.root=root;this.audit=audit;this.file=path.join(root,'state','snake-lab.json');this.state={format:'snake-lab/1',agent:{id:'snake-overwatch',authority:'NONE'},q:{},episodes:0,promotions:0};this._load();}
 _load(){try{const x=JSON.parse(fs.readFileSync(this.file,'utf8'));if(x?.format==='snake-lab/1')this.state={...this.state,...x,agent:{id:'snake-overwatch',authority:'NONE'}};}catch{}}
 _save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const t=this.file+'.tmp-'+process.pid;fs.writeFileSync(t,JSON.stringify(this.state));fs.renameSync(t,this.file);}
 _choose(s,r,eps,q=this.state.q){const k=key(s),row=q[k]||{};if(r()<eps)return ACTIONS[Math.floor(r()*4)];return ACTIONS.slice().sort((a,b)=>(row[b]||0)-(row[a]||0)||ACTIONS.indexOf(a)-ACTIONS.indexOf(b))[0];}
 _episode({seed=1,train=false,q=this.state.q,maxSteps=120}={}){const r=rng(seed),N=7;let body=[[3,3],[2,3]],apple=[5,3],score=0;for(let step=0;step<maxSteps;step++){const head=body[0];const occupied=new Set(body.map(x=>x.join(':')));const danger={};for(const a of ACTIONS){const [dx,dy]=V[a],nx=head[0]+dx,ny=head[1]+dy;danger[a]=nx<0||ny<0||nx>=N||ny>=N||occupied.has(nx+':'+ny);}const s={head,apple,danger};const a=this._choose(s,r,train?0.12:0,q),[dx,dy]=V[a],nh=[head[0]+dx,head[1]+dy];let reward=-0.01,done=false;if(danger[a]){reward=-1;done=true;}else{const ate=nh[0]===apple[0]&&nh[1]===apple[1];body.unshift(nh);if(ate){score++;reward=1;const free=[];const occ=new Set(body.map(x=>x.join(':')));for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(!occ.has(x+':'+y))free.push([x,y]);if(!free.length)done=true;else apple=free[Math.floor(r()*free.length)];}else body.pop();}
 if(train){const k=key(s),row=q[k]||(q[k]={}),old=row[a]||0;let next=0;if(!done){const h=body[0],occ=new Set(body.map(x=>x.join(':'))),d={};for(const z of ACTIONS){const [vx,vy]=V[z],nx=h[0]+vx,ny=h[1]+vy;d[z]=nx<0||ny<0||nx>=N||ny>=N||occ.has(nx+':'+ny);}const nr=q[key({head:h,apple,danger:d})]||{};next=Math.max(...ACTIONS.map(z=>nr[z]||0));}row[a]=old+0.25*(reward+0.9*next-old);}if(done)break;}return score;}
 _evaluate(q=this.state.q){const seeds=[101,202,303,404,505,606,707,808];const scores=seeds.map(seed=>this._episode({seed,q,train:false}));return{mean:scores.reduce((a,b)=>a+b,0)/scores.length,scores};}
 run({seed=1}={}){return{state:'SUCCESS',agent:this.state.agent,score:this._episode({seed,train:false}),policyStates:Object.keys(this.state.q).length};}
 improve({episodes=200}={}){episodes=Math.max(1,Math.min(5000,Number(episodes)||200));const before=this._evaluate(),candidate=JSON.parse(JSON.stringify(this.state.q));for(let i=0;i<episodes;i++)this._episode({seed:1000+this.state.episodes+i,train:true,q:candidate});const after=this._evaluate(candidate),promoted=after.mean>=before.mean;if(promoted){this.state.q=candidate;this.state.promotions++;}this.state.episodes+=episodes;this._save();this.audit?.('snake-lab',`candidate ${promoted?'promoted':'rejected'} after ${episodes} episodes`,'system');return{state:'SUCCESS',agent:this.state.agent,episodes,before,after,promoted,policyStates:Object.keys(this.state.q).length};}
 inventory(){const roots=['src','model','scripts','verification','research'];const rows=[];for(const rel of roots){const start=path.join(this.root,rel);if(!fs.existsSync(start))continue;const walk=d=>{for(const ent of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,ent.name);if(ent.isDirectory())walk(f);else{const st=fs.statSync(f);if(st.size>2*1024*1024)continue;rows.push({path:path.relative(this.root,f),bytes:st.size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});}}};walk(start);}return{state:'SUCCESS',agent:this.state.agent,files:rows.length,inventory:rows.slice(0,500),excluded:['state','data','.git','node_modules','.env','mental-health records']};}
 inspect(){return{state:'SUCCESS',agent:this.state.agent,episodes:this.state.episodes,promotions:this.state.promotions,policyStates:Object.keys(this.state.q).length,evaluation:this._evaluate(),constraints:['NO_SOURCE_PATCH_AUTHORITY','NO_SECURITY_MUTATION','NO_CAPABILITY_GRANTS','NO_MENTAL_HEALTH_ACCESS','PROPOSAL_ONLY_FOR_PRODUCTION_CHANGES']};}
 reset(confirm=''){if(String(confirm)!=='RESET SNAKE LEARNING')return{state:'DENIED',message:'Exact confirmation RESET SNAKE LEARNING is required.'};this.state={format:'snake-lab/1',agent:{id:'snake-overwatch',authority:'NONE'},q:{},episodes:0,promotions:0};this._save();return{state:'SUCCESS',reset:true,agent:this.state.agent};}
}
module.exports={SnakeLab};