import crypto from 'node:crypto';
import {GovernanceDb} from './governance-db.js';
function canonical(v){if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return `{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')}}`;return JSON.stringify(v);}
export function approvalBinding(input={}){const payload={actionEnvelopeId:input.actionEnvelopeId||null,taskId:input.taskId||null,operation:String(input.operation||''),arguments:input.arguments||{},capability:String(input.capability||''),actor:String(input.actor||'user:onechat'),toolVersion:String(input.toolVersion||'unknown')};return {payload,bindingHash:crypto.createHash('sha256').update(canonical(payload)).digest('hex')};}
export class ApprovalStore{
 constructor(stateRoot,audit=null){this.audit=audit;this.db=new GovernanceDb(stateRoot);}
 _strip(x){if(!x)return null;const y={...x};delete y._version;return y;}
 list({status=null,limit=100}={}){let rows=(this.db.list('approval',limit).records||[]).map(x=>this._strip(x));if(status)rows=rows.filter(x=>x.status===status);return rows;}
 get(id){const r=this.db.get('approval',id);return r.record?{...r.record,_version:r.version}:null;}
 _cas(id,fn,event){for(let i=0;i<5;i++){const cur=this.get(id);if(!cur)return null;const ver=cur._version;const base=this._strip(cur);const body=fn(base);const r=this.db.cas('approval',id,ver,body,event);if(r.state==='SUCCESS')return {...r.record,_version:r.version};if(r.state!=='CONFLICT')return null;}return null;}
 request(input={}){const now=Date.now(),bind=approvalBinding(input);const a={id:`approval-${crypto.randomUUID()}`,...bind.payload,bindingHash:bind.bindingHash,risk:String(input.risk||'high'),reason:String(input.reason||''),status:'PENDING',requestedAt:new Date(now).toISOString(),expiresAt:new Date(now+Math.max(60000,Number(input.expiresInMs)||3600000)).toISOString(),decidedAt:null,decision:null};const r=this.db.create('approval',a);if(r.state!=='SUCCESS')throw new Error(r.message||'Approval persistence failed.');this.audit?.append({type:'approval.request',approvalId:a.id,taskId:a.taskId,actionEnvelopeId:a.actionEnvelopeId,risk:a.risk,bindingHash:a.bindingHash});return a;}
 decide(id,decision){const d=String(decision||'').toUpperCase();if(!['APPROVE','DENY'].includes(d))return {state:'BLOCKED',message:'Decision must be APPROVE or DENY.'};const a=this.get(id);if(!a)return {state:'FAILURE',message:'Approval not found.'};if(a.status!=='PENDING')return {state:'BLOCKED',message:`Approval is already ${a.status}.`,approval:this._strip(a)};if(Date.now()>Date.parse(a.expiresAt)){const x=this._cas(id,v=>({...v,status:'EXPIRED',decidedAt:new Date().toISOString()}),{type:'expire'});return {state:'TIMEOUT',message:'Approval expired.',approval:this._strip(x)};}const x=this._cas(id,v=>({...v,status:d==='APPROVE'?'APPROVED':'DENIED',decision:d,decidedAt:new Date().toISOString()}),{type:'decision',decision:d});this.audit?.append({type:'approval.decision',approvalId:id,decision:d,bindingHash:a.bindingHash});return {state:d==='APPROVE'?'SUCCESS':'DENIED',message:`Approval ${x.status.toLowerCase()}.`,approval:this._strip(x)};}
 validate(id,expected={}){const a=this.get(id);if(!a)return {state:'DENIED',message:'Approval not found.'};if(a.status!=='APPROVED')return {state:'DENIED',message:`Approval status is ${a.status}.`,approval:this._strip(a)};if(Date.now()>Date.parse(a.expiresAt))return {state:'TIMEOUT',message:'Approval expired.',approval:this._strip(a)};const bind=approvalBinding({...a,...expected});if(bind.bindingHash!==a.bindingHash)return {state:'DENIED',message:'Approval binding does not match the exact operation.',expectedBinding:bind.bindingHash,actualBinding:a.bindingHash};return {state:'SUCCESS',message:'Exact operation approval is valid.',approval:this._strip(a)};}
}
