import crypto from 'node:crypto';
import {GovernanceDb} from './governance-db.js';
const RANK={low:0,medium:1,high:2,critical:3};
export class AutonomyStore{
 constructor(stateRoot,audit=null){this.audit=audit;this.db=new GovernanceDb(stateRoot);}
 _strip(x){if(!x)return null;const y={...x};delete y._version;return y;}
 list(){return (this.db.list('autonomy',1000).records||[]).map(x=>this._normalize(this._strip(x)));}
 get(id){const r=this.db.get('autonomy',id);return r.record?{...this._normalize(r.record),_version:r.version}:null;}
 _normalize(x){if(x.status==='ACTIVE'&&Date.now()>Date.parse(x.expiresAt))return {...x,status:'EXPIRED'};return x;}
 _cas(id,fn,event){for(let i=0;i<5;i++){const cur=this.get(id);if(!cur)return null;const ver=cur._version,base=this._strip(cur),body=fn(base);const r=this.db.cas('autonomy',id,ver,body,event);if(r.state==='SUCCESS')return {...r.record,_version:r.version};if(r.state!=='CONFLICT')return null;}return null;}
 grant({subject='user:onechat',agent='task-engine',scope=[],riskCeiling='medium',maxActions=10,durationMs=3600000}={}){const now=Date.now(),lease={id:`lease-${crypto.randomUUID()}`,subject,agent,scope:[...new Set((scope||[]).map(String))],riskCeiling:String(riskCeiling),maxActions:Math.max(1,Number(maxActions)||10),usedActions:0,status:'ACTIVE',createdAt:new Date(now).toISOString(),expiresAt:new Date(now+Math.max(60000,Number(durationMs)||3600000)).toISOString()};const r=this.db.create('autonomy',lease);if(r.state!=='SUCCESS')throw new Error(r.message||'Autonomy persistence failed.');this.audit?.append({type:'autonomy.grant',leaseId:lease.id,scope:lease.scope,riskCeiling:lease.riskCeiling,maxActions:lease.maxActions});return {state:'SUCCESS',message:'Bounded autonomy lease granted.',lease};}
 revoke(id){const a=this.get(id);if(!a)return {state:'FAILURE',message:'Autonomy lease not found.'};const x=this._cas(id,v=>({...v,status:'REVOKED',revokedAt:new Date().toISOString()}),{type:'revoke'});this.audit?.append({type:'autonomy.revoke',leaseId:id});return {state:'SUCCESS',message:'Autonomy lease revoked.',lease:this._strip(x)};}
 authorize(id,{operation='',risk='low'}={}){const a=this.get(id);if(!a)return {state:'DENIED',message:'Autonomy lease not found.'};const n=this._normalize(this._strip(a));if(n.status!=='ACTIVE')return {state:'DENIED',message:`Autonomy lease is ${n.status}.`,lease:n};if(n.usedActions>=n.maxActions)return {state:'DENIED',message:'Autonomy action limit exhausted.',lease:n};if(n.scope.length&&!n.scope.includes(operation))return {state:'DENIED',message:'Operation is outside autonomy scope.',lease:n};if((RANK[String(risk)]??3)>(RANK[n.riskCeiling]??1))return {state:'DENIED',message:'Operation exceeds autonomy risk ceiling.',lease:n};const x=this._cas(id,v=>({...v,usedActions:Number(v.usedActions||0)+1,lastUsedAt:new Date().toISOString()}),{type:'consume',operation,risk});return {state:'SUCCESS',message:'Autonomy lease authorizes this bounded operation.',lease:this._strip(x)};}
}
