import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
let DatabaseSync=null;try{({DatabaseSync}=require('node:sqlite'));}catch{}
const iso=()=>new Date().toISOString();

export class GovernanceDb{
  constructor(stateRoot=null){this.script=path.join(root,'storage','governance.py');this.dbPath=stateRoot?path.join(stateRoot,'governance.sqlite3'):path.join(root,'state','governance.sqlite3');fs.mkdirSync(path.dirname(this.dbPath),{recursive:true});this.native=!!DatabaseSync;if(this.native)this._openNative();}
  _openNative(){this.db=new DatabaseSync(this.dbPath);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS records(kind TEXT NOT NULL,id TEXT NOT NULL,version INTEGER NOT NULL,body_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(kind,id)); CREATE INDEX IF NOT EXISTS records_kind_updated_idx ON records(kind,updated_at DESC); CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,id TEXT NOT NULL,event_type TEXT NOT NULL,body_json TEXT NOT NULL,created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS events_record_idx ON events(kind,id,seq);`);}
  _py(payload){const p=spawnSync(process.env.PYTHON||'python3',[this.script],{cwd:root,input:JSON.stringify(payload),encoding:'utf8',timeout:15000,maxBuffer:4_000_000,env:{...process.env,IUV_GOV_DB:this.dbPath}});if(p.error)return {state:'UNAVAILABLE',message:p.error.message};if(p.status!==0)return {state:'ERROR',message:(p.stderr||p.stdout||`governance db exited ${p.status}`).slice(0,4000)};try{return JSON.parse((p.stdout||'{}').trim().split(/\n/).filter(Boolean).at(-1)||'{}');}catch{return {state:'ERROR',message:'Invalid governance DB response.'};}}
  status(){if(!this.native)return this._py({action:'status'});const rows=this.db.prepare('SELECT kind,COUNT(*) n FROM records GROUP BY kind').all();return {state:'SUCCESS',path:this.dbPath,journalMode:String(this.db.prepare('PRAGMA journal_mode').get().journal_mode||'wal'),backend:'node:sqlite',counts:Object.fromEntries(rows.map(r=>[r.kind,Number(r.n)]))};}
  get(kind,id){if(!this.native)return this._py({action:'get',kind,id});const r=this.db.prepare('SELECT body_json,version FROM records WHERE kind=? AND id=?').get(kind,id);return r?{state:'SUCCESS',record:JSON.parse(r.body_json),version:Number(r.version)}:{state:'FAILURE',message:'Record not found.'};}
  list(kind,limit=100){if(!this.native)return this._py({action:'list',kind,limit});const rows=this.db.prepare('SELECT body_json,version FROM records WHERE kind=? ORDER BY updated_at DESC LIMIT ?').all(kind,Math.max(1,Math.min(10000,Number(limit)||100)));return {state:'SUCCESS',records:rows.map(r=>({...JSON.parse(r.body_json),_version:Number(r.version)}))};}
  create(kind,body){if(!this.native)return this._py({action:'create',kind,id:body?.id,body});if(!body?.id)return {state:'BLOCKED',message:'id required'};const ts=iso();try{this.db.exec('BEGIN IMMEDIATE');this.db.prepare('INSERT INTO records(kind,id,version,body_json,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(kind,body.id,1,JSON.stringify(body),ts,ts);this.db.prepare('INSERT INTO events(kind,id,event_type,body_json,created_at) VALUES(?,?,?,?,?)').run(kind,body.id,'create',JSON.stringify(body),ts);this.db.exec('COMMIT');return {state:'SUCCESS',record:body,version:1};}catch(e){try{this.db.exec('ROLLBACK');}catch{}return {state:/unique|constraint/i.test(e.message)?'BLOCKED':'ERROR',message:e.message};}}
  cas(kind,id,expectedVersion,body,event={type:'update'}){if(!this.native)return this._py({action:'cas',kind,id,expectedVersion,body,event});const ts=iso();try{this.db.exec('BEGIN IMMEDIATE');const cur=this.db.prepare('SELECT version FROM records WHERE kind=? AND id=?').get(kind,id);if(!cur){this.db.exec('ROLLBACK');return {state:'FAILURE',message:'Record not found.'};}if(Number(cur.version)!==Number(expectedVersion)){this.db.exec('ROLLBACK');return {state:'CONFLICT',message:'Version conflict.',expected:Number(expectedVersion),actual:Number(cur.version)};}const nv=Number(expectedVersion)+1;const r=this.db.prepare('UPDATE records SET version=?,body_json=?,updated_at=? WHERE kind=? AND id=? AND version=?').run(nv,JSON.stringify(body),ts,kind,id,Number(expectedVersion));if(Number(r.changes)!==1){this.db.exec('ROLLBACK');return {state:'CONFLICT',message:'Concurrent update conflict.'};}this.db.prepare('INSERT INTO events(kind,id,event_type,body_json,created_at) VALUES(?,?,?,?,?)').run(kind,id,String(event.type||'update'),JSON.stringify(event),ts);this.db.exec('COMMIT');return {state:'SUCCESS',record:body,version:nv};}catch(e){try{this.db.exec('ROLLBACK');}catch{}return {state:'ERROR',message:e.message};}}
  events(kind,id){if(!this.native)return this._py({action:'events',kind,id});const rows=this.db.prepare('SELECT seq,event_type,body_json,created_at FROM events WHERE kind=? AND id=? ORDER BY seq').all(kind,id);return {state:'SUCCESS',events:rows.map(r=>({seq:Number(r.seq),type:r.event_type,body:JSON.parse(r.body_json),createdAt:r.created_at}))};}
  close(){try{this.db?.close();}catch{}}
}
