import crypto from "node:crypto";
const stop=new Set("a an and are as at be by for from has have he in is it its of on or that the this to was were will with you your".split(" "));
export function tokens(text){return [...new Set(String(text||"").toLowerCase().normalize("NFKC").match(/[\p{L}\p{N}]+/gu)||[])].filter(x=>x.length>1&&!stop.has(x));}
export function fingerprint(text){return crypto.createHash("sha256").update(tokens(text).sort().join("\n")).digest("hex");}
export function similarity(a,b){const A=new Set(tokens(a)),B=new Set(tokens(b));if(!A.size&&!B.size)return 1;let i=0;for(const x of A)if(B.has(x))i++;return i/(A.size+B.size-i||1);}
const neg=/\b(no|not|never|cannot|can't|isn't|aren't|without|false)\b/i;
export function compareClaims(a,b){const score=similarity(a,b);const polarityA=neg.test(String(a)),polarityB=neg.test(String(b));return {similarity:Number(score.toFixed(4)),relation:(polarityA!==polarityB&&score>=0.5)?"POTENTIAL_CONTRADICTION":score>=0.72?"NEAR_EQUIVALENT":score>=0.35?"RELATED":"DISTINCT",polarity:[polarityA?"negative":"positive",polarityB?"negative":"positive"]};}
export class KnowledgeEngine{
  constructor(store){this.store=store;}
  ingest(input){const text=String(input.text||"");const claims=text.split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(Boolean);const enriched=claims.map(c=>({text:c,fingerprint:fingerprint(c),tokens:tokens(c)}));const existing=this.store.list().slice(-200).map(m=>this.store.get(m.id)).filter(Boolean);const links=[];for(const c of enriched){for(const item of existing){for(const prior of item.analysis?.claims||[]){const priorText=typeof prior==="string"?prior:prior.text;const cmp=compareClaims(c.text,priorText);if(cmp.relation!=="DISTINCT")links.push({claim:c.text,knowledgeId:item.id,prior:priorText,...cmp});}}}const record=this.store.add({kind:"knowledge-analysis",title:input.title||"Knowledge analysis",source:input.source||"user/local",text,analysis:{claims:enriched,links}});return {state:"SUCCESS",message:`Stored ${claims.length} claims with ${links.length} cross-links.`,recordId:record.id,claims:enriched,links};}
  search(query,limit=10){return this.store.list().map(m=>this.store.get(m.id)).filter(Boolean).map(item=>({item,score:similarity(query,`${item.title||""} ${item.text||""}`)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>({id:x.item.id,title:x.item.title,kind:x.item.kind,source:x.item.source,score:Number(x.score.toFixed(4))}));}
  compareDefinition(term,description){const refs=this.store.list().map(m=>this.store.get(m.id)).filter(x=>x?.kind==="reference-definition"&&String(x.term||"").toLowerCase()===String(term||"").toLowerCase());if(!refs.length)return {state:"UNAVAILABLE",message:"No local reference-definition is available for that term. Import a licensed or otherwise legitimate reference source first."};return {state:"SUCCESS",term,comparisons:refs.map(r=>({referenceId:r.id,source:r.source,reference:r.definition,...compareClaims(description,r.definition)}))};}
}
