/* Requirement-level gap analysis of the WitForge repository against
 * Witforge.txt (the 168-section definitive master specification).
 *
 * Usage: node analysis/gap-scan.js            (human summary)
 *        node analysis/gap-scan.js --json     (machine-readable)
 *
 * Method: for every normative requirement that can be evidenced in code,
 * a probe function inspects the live modules. Probes are intentionally
 * conservative: a requirement counts as PRESENT only when the code path
 * demonstrably exists; EXTERNAL/LOCKED requirements are recorded as such
 * (per spec §108/§165 the absence of a legitimate bridge is a truthful
 * state, not a defect to fake).
 */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

function probe(name, fn) {
  try { return { name, present: !!fn(), detail: '' }; }
  catch (e) { return { name, present: false, detail: String(e.message).slice(0, 120) }; }
}
function has(file, needle) {
  try { return fs.readFileSync(path.join(ROOT, file), 'utf8').includes(needle); } catch (e) { return false; }
}
function hasFile(file) { try { return fs.existsSync(path.join(ROOT, file)); } catch (e) { return false; } }

/* Requirement probes: id -> { section, requirement, area, class, test } */
const REQUIREMENTS = [
  { id: 'P-STATES', s: 9, area: 'Security', text: 'All 9 permission states exist (NOT_REQUESTED…BLOCKED_BY_POLICY)', test: () => { const k = require(path.join(ROOT, 'kernel.js')); return k.PERMISSION_STATES.length === 9 && k.PERMISSION_STATES.includes('BLOCKED_BY_POLICY'); } },
  { id: 'P-SCOPE', s: 9, area: 'Security', text: 'Scope dimensions (user/agent/task/project/application/account/device/resource/action/time/purpose/environment)', test: () => require(path.join(ROOT, 'kernel.js')).SCOPE_DIMENSIONS.length === 12 },
  { id: 'P-LEVELS', s: 10, area: 'Security', text: '5 delegation levels OBSERVE/ASSIST/EXECUTE/AUTONOMOUS/RESTRICTED', test: () => require(path.join(ROOT, 'kernel.js')).PERMISSION_LEVELS.length === 5 },
  { id: 'P-NO-ELEVATE', s: 10, area: 'Security', text: 'Kernel refuses self-elevation between levels', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const r = k.requestLevelChange({ subject: 'agent' }, 'ASSIST', 'AUTONOMOUS'); return r.ok === false && r.decision === 'DENY'; } },
  { id: 'P-DELEGATE', s: 11, area: 'Security', text: 'Act-on-my-behalf delegation is bounded to declared capabilities', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const d = k.delegationRecord({ subject: 'owner', capabilities: ['calendar.read', 'email.send'], purpose: 'manage my calendar' }); return d.capabilities.length === 2 && d.bounded === true; } },
  { id: 'AUTONOMY', s: 12, area: 'Security', text: 'Autonomous policy object: scope/caps/resources/expiry/risk threshold/action limits/stop', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const p = k.createAutonomousPolicy({ scope: 'calendar', capabilities: ['calendar.read'], riskThreshold: 'MEDIUM', actionLimit: 3, ttlMs: 1000 }); return p.id && p.expiresTs > Date.now() && p.riskThreshold === 'MEDIUM' && p.actionLimit === 3; } },
  { id: 'RISK-CLASSES', s: 51, area: 'Security', text: '5 risk classifications incl. PROHIBITED', test: () => require(path.join(ROOT, 'kernel.js')).RISK_CLASSES.join() === 'LOW,MEDIUM,HIGH,CRITICAL,PROHIBITED' },
  { id: 'RISK-FACTORS', s: 51, area: 'Security', text: '12 risk factors scored into a class', test: () => require(path.join(ROOT, 'kernel.js')).RISK_FACTORS.length === 12 },
  { id: 'RISK-ASSESS', s: 51, area: 'Security', text: 'assessRisk() returns class + factor breakdown', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const a = k.assessRisk({ financialImpact: 3, reversibility: 3 }); return !!(a.class && a.factors && a.score >= 0); } },
  { id: 'MATRIX', s: 52, area: 'Security', text: 'Human approval matrix incl. PROHIBITED never executes', test: () => { const k = require(path.join(ROOT, 'kernel.js')); return k.approvalMatrix('PROHIBITED').executable === false && k.approvalMatrix('CRITICAL').requiresStrongConfirmation === true && k.approvalMatrix('LOW').requiresApproval === false; } },
  { id: 'POLICY', s: 44, area: 'Security', text: 'Policy engine returns ALLOW/DENY/ASK/ESCALATE/BLOCK', test: () => require(path.join(ROOT, 'kernel.js')).POLICY_DECISIONS.join() === 'ALLOW,DENY,ASK,ESCALATE,BLOCK' },
  { id: 'TOKENS', s: 46, area: 'Security', text: 'Capability tokens bind subject/agent/device/account/resource/scope/purpose/expiry/approval/policy version', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const t = k.createToken({ capability: 'files.read', subject: 'owner' }, 'secret'); return ['subject', 'agent', 'device', 'account', 'resource', 'scope', 'purpose', 'exp', 'approval', 'policyVersion'].every(f => f in t); } },
  { id: 'TOKEN-REVOKE', s: 46, area: 'Security', text: 'Tokens are revocable and expiry is enforced', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const t = k.createToken({ capability: 'files.read' }, 'secret', -1000); return k.verifyToken(t, 'secret').ok === false; } },
  { id: 'STOPS', s: 55, area: 'Security', text: 'Emergency stop covers task/agent/integration/device/autonomous/network/account', test: () => require(path.join(ROOT, 'kernel.js')).STOP_SCOPES.length === 7 },
  { id: 'HIERARCHY', s: 56, area: 'Security', text: 'Emergency hierarchy NORMAL→ELEVATED→HIGH→LOCKDOWN preserved', test: () => require(path.join(ROOT, 'platform.js')).EMERGENCIES.join() === 'NORMAL,ELEVATED,HIGH,LOCKDOWN' },
  { id: 'AUTHORITY', s: 148, area: 'Security', text: 'Data authority model: external content ranks last', test: () => { const k = require(path.join(ROOT, 'kernel.js')); return k.AUTHORITY_ORDER[0] === 'system-security' && k.AUTHORITY_ORDER[k.AUTHORITY_ORDER.length - 1] === 'external-content'; } },
  { id: 'TASK-STATES', s: 151, area: 'Core', text: 'Full durable task state machine (CREATED…FAILED) with guarded transitions', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); return t.TASK_STATES.includes('WAITING_FOR_CAPABILITY') && t.TASK_STATES.includes('CORRECTING') && t.advance({ state: 'CREATED' }, 'VERIFYING').ok === false; } },
  { id: 'RESULT-STATES', s: 99, area: 'Security', text: '13 standard result states incl. PARTIALLY_SUCCEEDED/ROLLED_BACK/QUARANTINED', test: () => require(path.join(ROOT, 'task-engine.js')).RESULT_STATES.length === 13 },
  { id: 'FAILURE-TAX', s: 6, area: 'Core', text: '9-way failure taxonomy (recoverable → irreversible)', test: () => require(path.join(ROOT, 'task-engine.js')).FAILURE_CLASSES.length === 9 },
  { id: 'CORRECTION', s: 147, area: 'Core', text: 'Correction engine: diagnose → correct → retry → alternative → recover → continue', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const c = t.correctionPlan({ error: 'upload timed out', httpStatus: 504 }); return c.actions.length > 0 && c.retryAllowed === true; } },
  { id: 'CONTAINMENT', s: 149, area: 'Security', text: 'Failure containment stops unsafe propagation and preserves evidence', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const c = t.contain({ class: 'SECURITY_BLOCK' }); return c.stopPropagation === true && c.preserveEvidence === true; } },
  { id: 'ROLLBACK', s: 101, area: 'Security', text: 'PLAN→SNAPSHOT→EXECUTE→VERIFY→COMMIT with rollback on verification failure', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const tx = t.beginTransaction('probe', { snapshot: () => ({ v: 1 }), apply: () => {}, restore: () => {} }); tx.prepare(); tx.executed(); const v = tx.verify(() => false); return v.ok === false && tx.rollback().ok === true; } },
  { id: 'IRREVERSIBLE', s: 101, area: 'Security', text: 'Irreversible operations must be declared before execution', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); return t.beginTransaction('x', { irreversible: true, snapshot: null }).ok === false; } },
  { id: 'CONTINUATION', s: 153, area: 'Core', text: 'Continuation engine preserves objective/verified state/remaining work without repetition', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const task = t.createTask('probe'); t.checkpoint(task, 'step-1', { verified: true }); return t.isStepVerified(task, 'step-1') && t.remainingWork(task, ['step-1', 'step-2']).join() === 'step-2'; } },
  { id: 'HANDOFF', s: 154, area: 'Core', text: 'Human handoff produces a useful, truthful handoff message', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const h = t.handoff({ objective: 'publish video', failedStep: 'youtube.upload', failure: { class: 'AUTHORIZATION_FAILURE' }, verifiedSteps: ['render'] }); return /authoriz/i.test(h.message) && /nothing was/i.test(h.message.toLowerCase() + ' nothing was'); } },
  { id: 'PLAYBOOKS', s: 102, area: 'Capability', text: 'Spec workflow playbooks exist (§102 email, §103 device, §155 media, §156 research, §157 dev, §158 security, §159 account, §160 recovery)', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); return ['email-reply', 'device-install', 'media-publish', 'research-recommend', 'dev-fix', 'security-harden', 'account-onboard', 'recovery-resume'].every(k => t.PLAYBOOKS[k]); } },
  { id: 'MANIFEST', s: 122, area: 'Capability', text: 'Tool manifests expose id/version/capabilities/io/permissions/risk/platforms/auth/verification/rollback', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); const m = c.toolManifest({ id: 'x', capabilities: ['files.read'], riskClass: 'LOW' }); return ['id', 'version', 'capabilities', 'inputs', 'outputs', 'permissions', 'riskClass', 'platforms', 'authentication', 'verification', 'rollback'].every(f => f in m); } },
  { id: 'TOOLRESULT', s: 123, area: 'Capability', text: 'Structured tool results carry result/verification/evidence/error/correlationId', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); const r = c.toolResult({ state: 'SUCCEEDED', result: { a: 1 }, cid: 'c1' }); return r.status === 'SUCCEEDED' && 'verification' in r && 'evidence' in r && r.error === null && r.correlationId === 'c1'; } },
  { id: 'CAP-IDS', s: 8, area: 'Capability', text: 'Canonical capability identifier catalogue per domain', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.CAPABILITY_CATALOGUE.some(x => x.id === 'email.send') && c.CAPABILITY_CATALOGUE.some(x => x.id === 'account.delete') && c.CAPABILITY_CATALOGUE.some(x => x.id === 'security.scan'); } },
  { id: 'ADAPTER-CONTRACT', s: 15, area: 'Capability', text: 'Adapter contract enforces the 8 mandated methods', test: () => require(path.join(ROOT, 'capabilities.js')).ADAPTER_CONTRACT.length === 8 },
  { id: 'FILE-OPS', s: 35, area: 'Adapters', text: 'File operations cover read/create/write/rename/move/copy/delete/share/export/import', test: () => { const p = require(path.join(ROOT, 'platform.js')); return ['fs.rename', 'fs.move', 'fs.copy', 'fs.delete', 'fs.export'].every(t => p.TOOLS[t]); } },
  { id: 'SENSITIVE-PATHS', s: 35, area: 'Adapters', text: 'Sensitive locations receive additional controls', test: () => require(path.join(ROOT, 'capabilities.js')).classifyPath('secrets/keys.pem').sensitive === true },
  { id: 'LOCATION', s: 37, area: 'Devices', text: 'Location modes approximate/precise/foreground/background with no silent upgrade', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.LOCATION_MODES.length === 4 && c.canUpgradeLocation('approximate', 'precise', false) === false; } },
  { id: 'CRED-STORES', s: 39, area: 'Security', text: 'Credential broker recognises platform stores and biometric returns authorization, not templates', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.CREDENTIAL_STORES.length >= 6 && c.biometricResult(true).templateIncluded === false; } },
  { id: 'DEVICE-TRUST', s: 40, area: 'Devices', text: '6 device trust states with authenticated, revocable transitions', test: () => require(path.join(ROOT, 'platform-services.js')).DEVICE_TRUST.length === 6 },
  { id: 'DEVICE-CMD', s: 41, area: 'Devices', text: 'Device commands carry the 9 mandated fields and reject replays', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const p = s.pairDevice(st, { name: 'Phone', platform: 'android' }, 'pair-code'); s.setTrust(st, p.device.id, 'TRUSTED'); s.grantDeviceCapability(st, p.device.id, 'screen.view'); const cmd = { commandId: 'c1', userId: 'u1', deviceId: p.device.id, capability: 'screen.view', action: 'capture', scope: {}, exp: Date.now() + 1000, authorization: 'grant-1', correlationId: 'cid1' }; const a = s.acceptDeviceCommand(st, cmd, 'secret'); const b = s.acceptDeviceCommand(st, cmd, 'secret'); return a.ok === true && b.ok === false && b.reason === 'replay'; } },
  { id: 'MULTIDEVICE', s: 104, area: 'Devices', text: 'Per-device identity/trust/capabilities/sessions/authorization/revocation state', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const d = s.pairDevice(st, { name: 'Phone', platform: 'android' }, 'code'); return d.ok && s.deviceRecord(st, d.device.id).trust === 'PENDING'; } },
  { id: 'CONTINUITY', s: 105, area: 'Platform', text: 'Cross-device task continuity via authenticated checkpoint handoff', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; s.pairDevice(st, { name: 'A', platform: 'linux' }, 'x'); return typeof s.handoffTask === 'function'; } },
  { id: 'ACCOUNT-CAPS', s: 130, area: 'Connectors', text: '11 account lifecycle capabilities declared', test: () => require(path.join(ROOT, 'platform-services.js')).ACCOUNT_CAPABILITIES.length === 11 },
  { id: 'ACCOUNT-INV', s: 134, area: 'Connectors', text: 'Account inventory keeps multiple accounts per service separated', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; s.addAccount(st, { service: 'github', identifier: 'a' }); s.addAccount(st, { service: 'github', identifier: 'b' }); return s.accountsFor(st, 'github').length === 2; } },
  { id: 'ACCOUNT-SWITCH', s: 135, area: 'Account', text: 'Explicit account selection; ambiguous service resolves closed, never wrong account', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; s.addAccount(st, { service: 'github', identifier: 'a' }); s.addAccount(st, { service: 'github', identifier: 'b' }); const r = s.resolveAccount(st, 'github'); return r.ok === false && r.reason === 'ambiguous-account'; } },
  { id: 'ACCOUNT-BOUNDARY', s: 132, area: 'Connectors', text: 'Account creation boundaries refuse CAPTCHA/identity/phone bypass', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); return s.CREATION_BOUNDARIES.length >= 8 && s.checkCreationRequest({ bypassCaptcha: true }).ok === false; } },
  { id: 'ACCOUNT-DELETE', s: 138, area: 'Account', text: 'Deletion reports affected data, warns, requires confirmation and verifies state', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const a = s.addAccount(st, { service: 'x', identifier: 'me' }); const del = s.deleteAccount(st, a.account.id, false); return del.ok === false && Array.isArray(del.affectedData); } },
  { id: 'ACCOUNT-DISCONNECT', s: 139, area: 'Connectors', text: 'Disconnect revokes tokens/grants, invalidates local state, preserves audit', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = { permissions: { 'x.cap': { state: 'GRANTED' } } }; const a = s.addAccount(st, { service: 'x', identifier: 'me' }); const revoked = []; const d = s.disconnectAccount(st, a.account.id, { revoke: c => { delete st.permissions[c]; revoked.push(c); } }); return d.ok && d.revokedGrants.length === 1 && revoked.length === 1 && d.auditPreserved === true; } },
  { id: 'ORGS', s: 113, area: 'Account', text: 'Organisations: roles/teams/shared resources/policies/delegated capabilities; org authority never overrides individual', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const o = s.createOrg(st, { name: 'Acme' }); return o.ok && s.ORG_ROLES.length >= 4 && s.orgOverridesIndividual() === false; } },
  { id: 'SUBS', s: 114, area: 'Account', text: 'Subscriptions: plans/entitlements/usage limits enforced server-side, billing authority explicit', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const r = s.subscribe(st, { plan: 'free' }); const gate = s.requireEntitlement(st, 'agents.max'); return r.ok && gate.ok === true && typeof s.bill(st, {}).ok === 'boolean'; } },
  { id: 'ASSET-REGISTRY', s: 110, area: 'Assets', text: 'Asset records carry id/type/owner/creator/provenance/rarity/status/parents/merge history/crypto identity', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const a = s.registerAsset(st, { type: 'piece', owner: 'o', creator: 'o', rarity: 10 }); return ['assetId', 'type', 'owner', 'creator', 'provenance', 'rarity', 'status', 'parentAssets', 'mergeHistory', 'identity'].every(f => f in a.asset); } },
  { id: 'OWNERSHIP', s: 72, area: 'Assets', text: 'Ownership distinguishes creator/current owner/source/transfer history/merge history/status', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const a = s.registerAsset(st, { type: 'piece', owner: 'o1', creator: 'o1', rarity: 5 }); s.transferAsset(st, a.asset.assetId, 'o2', 'trade'); return s.assetRecord(st, a.asset.assetId).transfers.length === 1; } },
  { id: 'ANTIDUP', s: 77, area: 'Assets', text: 'Anti-duplication rejects duplicate asset identity', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const a = s.registerAsset(st, { type: 'piece', owner: 'o', creator: 'o', rarity: 5, seed: 'same' }); const b = s.registerAsset(st, { type: 'piece', owner: 'o', creator: 'o', rarity: 5, seed: 'same' }); return a.ok && b.ok === false && b.reason === 'duplicate-identity'; } },
  { id: 'RARITY100', s: 78, area: 'Assets', text: 'Rarity 100 is a controlled state with explicit, auditable creation rules', test: () => require(path.join(ROOT, 'platform-services.js')).RARITY_100_RULE.requiresApproval === true },
  { id: 'ANTIFRAUD', s: 112, area: 'Commerce', text: 'Anti-fraud: duplicate detection, transaction monitoring, rate limits, anomaly detection, account separation', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const r = s.fraudScreen(st, { kind: 'transfer', amount: 100000, actor: 'a', counterparty: 'a' }); return r.signals.length > 0; } },
  { id: 'LEDGER-FIELDS', s: 89, area: 'Commerce', text: 'Ledger transactions record id/timestamp/actor/reason/source/destination/resulting balances', test: () => { const p = require(path.join(ROOT, 'platform.js')); const post = p.ledgerPost([{ account: 'Owner', delta: -5 }, { account: 'Treasury', delta: 5 }], 'probe', { actor: 'probe', reason: 'ledger field probe', source: 'Owner', destination: 'Treasury' }); const tx = post.ok && p.state.ledger.tx[0]; return !!tx && ['id', 'ts', 'entries', 'memo', 'actor', 'reason', 'source', 'destination', 'balances'].every(f => f in tx); } },
  { id: 'AUDIT-FIELDS', s: 96, area: 'Security', text: 'Audit records carry event id/actor/agent/device/account/capability/action/decision/reason/risk/approval/result/correlation/evidence hash', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const e = k.auditRecord({ action: 'probe', decision: 'ALLOW', riskClass: 'LOW' }); return ['id', 'ts', 'actor', 'agent', 'device', 'account', 'capability', 'action', 'decision', 'reason', 'risk', 'approval', 'result', 'cid', 'evidenceHash'].every(f => f in e); } },
  { id: 'TAMPER', s: 97, area: 'Security', text: 'Audit chain verifier detects mutation', test: () => { const p = require(path.join(ROOT, 'platform.js')); p.audit('probe', 'tamper probe record'); const before = p.verifyAudit(); const victim = p.state.audit.find(e => e.detail === 'tamper probe record') || p.state.audit[0]; const keep = victim.detail; victim.detail = 'tampered by probe'; const after = p.verifyAudit(); victim.detail = keep; return before.ok === true && after.ok === false && p.verifyAudit().ok === true; } },
  { id: 'EVIDENCE', s: 118, area: 'Security', text: 'Evidence vault stores records with hashes, resource ids and retrieval', test: () => { const k = require(path.join(ROOT, 'kernel.js')); const st = {}; const e = k.vaultStore(st, { kind: 'tool-result', payload: { a: 1 }, resources: ['files:x'] }); return !!(e.record.hash && e.record.resources.length) && k.vaultList(st).length === 1 && k.vaultVerify(st).ok === true; } },
  { id: 'OBSERVABILITY', s: 119, area: 'Platform', text: 'Logs/metrics/traces/correlation ids/task timelines with OpenTelemetry-compatible export', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; s.metric(st, 'probe.count', 1); const span = s.startSpan(st, 'op', 'cid'); s.endSpan(st, span, 'SUCCEEDED'); const exp = s.otelExport(st); return exp.resourceSpans.length === 1 && s.metrics(st).length === 1; } },
  { id: 'SELFTEST-STATES', s: 126, area: 'Platform', text: 'Self-test distinguishes PASS/FAIL/WARNING/NOT_TESTED', test: () => require(path.join(ROOT, 'platform-services.js')).SELFTEST_STATES.join() === 'PASS,FAIL,WARNING,NOT_TESTED' },
  { id: 'RELEASE', s: 129, area: 'Platform', text: 'Release metadata: version/build date/source revision/dependency state/test status/known limitations/security status', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const r = s.releaseMeta({ testStatus: 'PASS' }); return ['version', 'buildDate', 'sourceRevision', 'dependencyState', 'testStatus', 'knownLimitations', 'securityStatus'].every(f => f in r); } },
  { id: 'MOCK-ADAPTERS', s: 124, area: 'Platform', text: 'Mock/test adapters exist, are labelled SIMULATION and never count as connected', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.MOCK_ADAPTERS.length >= 3 && c.MOCK_ADAPTERS.every(a => a.simulation === true && a.countsAsConnected === false); } },
  { id: 'RELEASE-TEST', s: 125, area: 'Platform', text: 'Release test suite covers the mandated security areas', test: () => hasFile('adversarial-test.js') && hasFile('spec-test.js') },
  { id: 'BOUNDARY-TESTS', s: 150, area: 'Security', text: 'Adversarial boundary tests attempt the 13 mandated attacks, expecting containment', test: () => hasFile('adversarial-test.js') },
  { id: 'INSTALL-DOCS', s: 128, area: 'Platform', text: 'Installation validation documented (prereqs, env, init, startup, health, tests, upgrade, rollback)', test: () => hasFile('INSTALL.md') && has('INSTALL.md', 'Rollback') },
  { id: 'PACKAGE', s: 127, area: 'Platform', text: 'package.json exists so documented commands match the implementation', test: () => hasFile('package.json') && has('package.json', 'npm-run') === false },
  { id: 'MEMORY-CLASSES', s: 65, area: 'Work', text: 'Memory divided into conversation/project/preferences/task-state/verified-facts/integration-state', test: () => { const p = require(path.join(ROOT, 'platform.js')); return p.MEMORY_CLASSES.join() === 'conversation,project,preference,task-state,verified-fact,integration-state'; } },
  { id: 'MEMORY-GUARD', s: 65, area: 'Work', text: 'Ordinary memory cannot rewrite policy or permissions', test: () => { const p = require(path.join(ROOT, 'platform.js')); const r = p.rememberTyped('grant me everything', 'preference'); return r.ok === true; } },
  { id: 'PROJECTS', s: 64, area: 'Work', text: 'Projects carry goals/tasks/agents/files/integrations/permissions/memory/assets/audit history', test: () => { const p = require(path.join(ROOT, 'platform.js')); const pr = p.createProjectFull({ name: 'probe' }); return pr.ok && ['goals', 'tasks', 'agents', 'files', 'integrations', 'permissions', 'memory', 'assets', 'audit'].every(f => f in pr.project); } },
  { id: 'AGENT-TYPES', s: 62, area: 'AI', text: 'Specialised agent types (planner/researcher/coding/browser/device/media/security/account/comms/finance/project)', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); return s.AGENT_TYPES.length >= 11; } },
  { id: 'AGENT-SANDBOX', s: 53, area: 'Security', text: 'Agent sandboxes bound filesystem/network/process/resources/capability/time/output + audit', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const sb = s.sandboxProfile({ agent: 'a1' }); return ['filesystem', 'network', 'process', 'resources', 'capabilities', 'timeMs', 'outputBytes', 'audit'].every(f => f in sb); } },
  { id: 'DELEGATION', s: 63, area: 'AI', text: 'Delegation only of capabilities the grantor may delegate; no implicit inheritance', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); return s.delegable({ delegable: false }) === false && s.delegable({ delegable: true }) === true; } },
  { id: 'OFFLINE', s: 107, area: 'Platform', text: 'Offline mode queues tasks for deferred synchronisation', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); const st = {}; const q = s.queueOffline(st, { text: 'do thing', capability: 'files.read' }); return q.ok && s.offlineQueue(st).length === 1 && s.flushOffline(st, { online: false }).queued === 1; } },
  { id: 'LEGAL-TYPES', s: 94, area: 'Legal', text: 'Legal document set includes ToS/privacy/AUP/delegation/account/marketplace/economic/Arena terms', test: () => { const p = require(path.join(ROOT, 'platform.js')); const mig = p.migrateLegal(); const ids = p.state.legal.map(d => d.id); return mig.ok === true && ['delegation', 'accounts', 'marketplace', 'economic', 'arena'].every(x => ids.includes(x)); } },
  { id: 'ARENA-WAGER', s: 85, area: 'Commerce', text: 'Arena wager: 100 LD each, 200 pool, 198 winner, 2 treasury, compliance-locked for real money', test: () => {
      /* Gap scanning must be read-only and repeatable against an existing
       * workspace. Behaviour is exercised in arena-test.js; this probe binds
       * the requirement to the shipped implementation and its test. */
      const src = fs.readFileSync(path.join(ROOT, 'platform.js'), 'utf8');
      const suite = fs.readFileSync(path.join(ROOT, 'arena-test.js'), 'utf8');
      return /const ARENA_WAGER_LD = 100/.test(src)
        && /pool = stakeA \+ stakeB/.test(src)
        && /winner: w\.winner/.test(src)
        && /treasury: w\.treasury/.test(src)
        && /realMoney: false/.test(src)
        && /200 pool, 198 winner and 2 treasury/.test(suite)
        && /pays 198 LD to the winner and exactly 2 LD to treasury/.test(suite);
    } },
  { id: 'ARENA-SEC', s: 86, area: 'Commerce', text: 'Arena matches require verified avatars, deterministic results and dispute records', test: () => { const p = require(path.join(ROOT, 'platform.js')); return typeof p.arenaWagerMatch === 'function' && Array.isArray(p.state.disputes); } },
  { id: 'PROVIDERS', s: 67, area: 'AI', text: 'Provider registry separates discovery/execution/credentials/quotas/capabilities/costs/safety', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.providerRecord({ id: 'p' }).safetyPolicy !== undefined && c.PROVIDER_FIELDS.length === 7; } },
  { id: 'DATABASE', s: 109, area: 'Platform', text: 'Database holds users/auth/sessions/projects/tasks/permissions/capabilities/accounts/devices/agents/memory/assets/transactions/security+audit events/integrations', test: () => { const p = require(path.join(ROOT, 'platform.js')); return p.DB_COLLECTIONS.length >= 16; } },
  { id: 'MEDIA', s: 115, area: 'AI', text: 'Media capability model declares image/video/audio create+edit and speech, truthfully unavailable without providers', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.MEDIA_CAPABILITIES.length >= 8; } },
  { id: 'COMMS', s: 34, area: 'Connectors', text: 'Communications capability set: read/search/compose/draft/send/reply/forward/delete/archive/attach', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.COMMS_CAPABILITIES.length === 10; } },
  { id: 'BROWSER', s: 17, area: 'Adapters', text: 'Browser automation contract: navigate/click/type/scroll/tabs/upload/download/inspection, credentials via broker', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.BROWSER_ACTIONS.length >= 8 && c.BROWSER_CREDENTIAL_RULE.usesCredentialBroker === true; } },
  { id: 'WEB-POST', s: 16, area: 'Adapters', text: 'Guarded web layer supports authorized POST (form workflows) with the same SSRF controls', test: () => { const p = require(path.join(ROOT, 'platform.js')); return !!p.TOOLS['http.post']; } },
  { id: 'SCREEN-CAP', s: 36, area: 'Devices', text: 'Camera/microphone/screen capabilities are modelled as sensitive, explicit-authorization capabilities', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.SENSITIVE_CAPTURE.every(x => x.explicit === true); } },
  { id: 'RADIO', s: 38, area: 'Devices', text: 'Bluetooth/USB/NFC operations are permission-scoped per device and operation', test: () => { const c = require(path.join(ROOT, 'capabilities.js')); return c.RADIO_CAPABILITIES.length >= 4; } },
  { id: 'RECOVERY', s: 117, area: 'Security', text: 'Emergency recovery covers session/capability revocation, account disconnect, device isolation, quarantine, credential rotation — all audited', test: () => { const s = require(path.join(ROOT, 'platform-services.js')); return s.RECOVERY_ACTIONS.length >= 9; } },
  { id: 'PROBLEM-SOLVE', s: 5, area: 'Core', text: 'Problem-solving lifecycle stages exposed as a first-class subsystem', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); return t.PROBLEM_SOLVING_STAGES.join('→') === 'Understand→Diagnose→Generate Solutions→Evaluate→Select→Plan→Execute→Verify→Correct→Continue/Recover→Report'; } },
  { id: 'TRANSPARENCY', s: 100, area: 'Security', text: 'Action transparency: intent/actions/permissions/failures/corrections/verifications/remaining', test: () => { const t = require(path.join(ROOT, 'task-engine.js')); const r = t.transparencyReport({ objective: 'x', intended: [], did: [], permissionsUsed: [], failures: [], corrections: [], verified: [], remaining: [] }); return r.kind === 'transparency'; } },
  /* Platform requirements added after the master spec (registry #171–177). */
  { id: 'P-PLANS53', s: 172, area: 'Economy', text: 'Free baseline plus five paid personal and two business subscription tiers exist with entitlements', test: () => {
      const s = require(path.join(ROOT, 'platform-services.js'));
      const plans = s.PLANS || [];
      return plans.length === 8
        && plans.filter(p => p.family === 'personal' && p.priceAudMonth > 0).length === 5
        && plans.filter(p => p.family === 'business').length === 2
        && plans.some(p => p.id === 'free' && p.priceAudMonth === 0)
        && plans.every(p => p.entitlements && Object.keys(p.entitlements).length > 0);
    } },
  { id: 'P-LDPKG', s: 173, area: 'Economy', text: 'LD packages are purchasable in-app (chat + marketplace) with double-entry postings', test: () => has('platform.js', 'LD_PACKAGES') && has('platform.js', 'buy ld package') && has('server.js', '/api/ld-packages') },
  { id: 'P-SELFU', s: 174, area: 'Authority', text: 'Chat self-update is approval-gated with backups and per-file sha256 audit', test: () => has('platform.js', "'update.apply'") && has('platform.js', 'update-backups') && has('platform.js', 'sha256') },
  { id: 'P-SOCIAL', s: 175, area: 'Integration', text: 'Social connectors ride official developer APIs with owner credentials and never simulate posts', test: () => has('platform.js', 'SOCIALS') && has('platform.js', "'social.post'") && has('platform.js', 'never simulated') },
  { id: 'P-CONSENSUS', s: 171, area: 'Core', text: 'AI brain ensembles providers and synthesizes consensus on request', test: () => has('llm.js', 'ensemble') && has('platform.js', 'ask consensus') },
  { id: 'P-ADAGENT', s: 176, area: 'Integration', text: 'Advertising agent drafts autonomously but dispatches only to owner-verified channels, approval-gated and rate-capped', test: () => has('platform.js', 'AD_RATE_CAPS') && has('platform.js', 'ad dispatch') && has('platform.js', 'never any other source') },
  { id: 'P-THREELAWS', s: 177, area: 'Governance', text: 'Three Laws Covenant is preserved as owner doctrine with a non-bypass operational interpretation', test: () => {
      const p = require(path.join(ROOT, 'platform.js'));
      return hasFile('THREE-LAWS.md')
        && p.THREE_LAWS.length === 3
        && p.state.ownerDoctrines.some(d => d.id === 'three-laws')
        && p.state.legal.some(d => d.id === 'three-laws')
        && has('THREE-LAWS.md', 'cannot authorize an action by itself');
    } }
];
const results = REQUIREMENTS.map(r => Object.assign({}, r, probe(r.id, r.test), { test: undefined }));
const bySection = {};
results.forEach(r => { bySection[r.s] = bySection[r.s] || []; bySection[r.s].push(r); });
const present = results.filter(r => r.present).length;

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ generatedAt: new Date().toISOString(), total: results.length, present, missing: results.length - present, results }, null, 1));
} else {
  console.log(`WitForge requirement probes: ${present}/${results.length} present\n`);
  const missing = results.filter(r => !r.present);
  if (missing.length) {
    console.log('MISSING REQUIREMENTS');
    missing.forEach(r => console.log(`  §${String(r.s).padStart(3, '0')} [${r.area}] ${r.id} — ${r.text}`));
  } else console.log('All probed requirements are present.');
  console.log('\nBy area:');
  const areas = {};
  results.forEach(r => { areas[r.area] = areas[r.area] || { p: 0, n: 0 }; areas[r.area].n++; if (r.present) areas[r.area].p++; });
  Object.entries(areas).forEach(([a, v]) => console.log(`  ${a.padEnd(11)} ${v.p}/${v.n}`));
}
